### ISSUE TITLE
clace.sock file not created on Mac

### ISSUE THREAD

**Issue by gedw99** [claceio/clace#24]
I just hit an Issue with the socket creation file...  

I set the CL_HOME to a different place and now the server panics with:
```sh
clace --config-file /Users/apple/workspace/clace/clace.toml server start
Error starting server: error removing socket file /Users/apple/workspace/clace/clace/.data/run/clace.sock : remove /Users/apple/workspace/go/clace/clace/.data/run/clace.sock: no such file or directory
```
It's a race condition perhaps, because on the previous "server start" I was not using CL_HOME, and so the socket file was in a different folder - the one I was kicking off Clase from.

**Comment by gedw99** [comment]
What do you consider Best Practice ?

Have the Config file in HOME/clase/clase.toml
Have the CL_HOME point to  a place that would be a Volume that can be reused between server restarts  ?

**Comment by gedw99** [comment]
I am now stuck and cant run clace :)

It really wants that old sockets file...

**Comment by gedw99** [comment]
Cant kill it either...

ps -ax | grep clace                                  
65576 ttys012    0:00.00 grep clace
apple@apples-MacBook-Pro clace % kill -9 65576      
kill: kill 65576 failed: no such process

**Comment by infoclace** [comment]
```export CL_HOME=/Users/apple/workspace/clace/clace/clace.toml```
is the issue I think. CL_HOME should point to the home folder, not to the config file

**Comment by gedw99** [comment]
ok, git pull, go rebuild and here we go: 

```sh

mkdir -p /Users/apple/workspace/clace/clace/.data
cp clace.toml /Users/apple/workspace/clace/clace/.data/clace.toml
clace server start -c -l trace
4:22PM INF clace/internal/types/logger.go:52 > Logger initialized  backups=10 loglevel=trace maxSizeMB=50
4:22PM INF clace/internal/metadata/metadata.go:47 > Connecting to DB dbPath=/Users/apple/workspace/clace/clace/.data/clace.db
4:22PM INF clace/internal/metadata/metadata.go:91 > DB version is current
4:22PM TRC clace/internal/server/server.go:170 > Container management command cmd=docker
4:22PM WRN clace/internal/server/router.go:126 > Admin API access over TCP is enabled, enable 2FA for admin user account
4:22PM DBG clace/internal/server/server.go:238 > Error creating socket file, trying to dial socket file /Users/apple/workspace/clace/clace/.data/run/clace.sock error="listen unix /Users/apple/workspace/clace/clace/.data/run/clace.sock: bind: invalid argument"
4:22PM DBG clace/internal/server/server.go:241 > Error dialling UDS, trying to remove socket file error="dial unix /Users/apple/workspace/clace/clace/.data/run/clace.sock: connect: invalid argument"
Error starting server: error removing socket file /Users/apple/workspace/clace/clace/.data/run/clace.sock : remove /Users/apple/workspace/clace/clace/.data/run/clace.sock: no such file or directory. Original error listen unix /Users/apple/workspace/clace/clace/.data/run/clace.sock: bind: invalid argument 

```

**Comment by gedw99** [comment]
wil do..

here is there config btw

```toml

# The default configuration used by the Clace server and client

server_uri = "$CL_HOME/run/clace.sock" # the unix domain socket (UDS) path or URL to the Clace server
admin_user = "admin"

# Properties use by the Clace client to connect to the server
[client]
admin_password = "password"     # the password for the admin user. Required only if admin over TCP is enabled
skip_cert_check = false

# HTTP port binding related Config
[http]
host = "127.0.0.1" # bind to localhost by default for HTTP
port = 25222       # default port for HTTP

# HTTPS port binding related Config
[https]
host = "0.0.0.0"                               # bind to all interfaces (if port is >= 0)
port = 25223                                   # port for HTTPS
enable_cert_lookup = true                      # enable looking for certificate files on disk before using Let's Encrypt
service_email = ""                             # email address for registering with Let's Encrypt. Set a value to enable automatic certs
use_staging = true                             # use Let's Encrypt staging server
cert_location = "$CL_HOME/config/certificates" # where to look for existing certificate files
storage_location = "$CL_HOME/run/certmagic"    # where to cache dynamically created certificates

[security]
admin_over_tcp = true            # enable admin API's over TCP (HTTP/HTTPS). Admin is over UDS only by default
admin_password_bcrypt = ""       # the password bcrypt value
app_default_auth_type = "system"   # default auth type for new apps, "system" or "none" or custom auth
session_secret = ""              # the secret key for session cookie. Auto generated on server startup if not set
session_max_age = 86400          # session max age in seconds
session_https_only = true        # session cookie is HTTPS only

# Logging related Config
[logging]
level = "INFO"
max_backups = 10
max_size_mb = 50
console = false
file = true
access_logging = true

# Metadata Storage Config
[metadata]
db_connection = "sqlite:$CL_HOME/clace.db"
auto_upgrade = true

[system]
tailwindcss_command = "tailwindcss"
file_watcher_debounce_millis = 300
node_path = ""                      # node module lookup paths https://esbuild.github.io/api/#node-paths
container_command = "auto"          # "auto" or "docker" or "podman"

[plugin."store.in"]
db_connection = "sqlite:$CL_HOME/clace_app.db"

```
